#!/bin/bash
filename="$1"
t="navigate"
while read -r line
do
	name="$line"
	curl -i localhost:8000 -X POST -d '{"message": "Broadsword was here ;)", "userID": "'$name'", "noticeType": "IMPORTANT"}'
done <"$filename"
